# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VROIo63N4RvwTxahzHBWK_FX6JiTlAoO
"""

!apt install -qq enchant
!pip install pyenchant
import enchant

import re

url = input ('ENTER A WIKIPEDIA URL:')

htmlfile = urllib.request.urlopen(url)
soup = BeautifulSoup(htmlfile, 'lxml')
text = soup.get_text()
tokens = re.findall("\s*(\w*)\s*", text, re.UNICODE) 



# while("" in tokens) :
#     tokens.remove("") 

tokens = ' '.join(tokens).split()

d = enchant.Dict("en_US")
tokens = [tok for tok in tokens if d.check(tok)]
tokens = set(tokens)
no_nums = set()
for tok in tokens:
  if (not tok.isnumeric()):
    no_nums.add(tok)

print(no_nums)
# newlist = []
# for tok in tokens: 
#   if (tok not in newlist): 
#       newlist.append(i)

# print(newlist)

with open('/content/drive/MyDrive/Web Scraping.txt', 'w') as writefile:
    for tok in no_nums:
      writefile.write( tok + "\n")

writefile.close